### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by sleepy-maker** [nopivnick/creaturely-life#2]
For creating class, you need to think about your current folder structure.
I guess you just pushed a folder which you downloaded from p5 online editor.

For example,
js files which are related to p5 should be under `lib` folder.
basically people manage js files they make and js libraries separately.

**Comment by nopivnick** [comment]
> I guess you just pushed a folder which you downloaded from p5 online editor.

yes. I had been working in the online editor but -- as you've pointed out elsewhere -- it's unreliable. after losing 6 or 7 hours of work despite constant saves I decided it was time to work locally.

I will make your recommended changes to folder structure once I finish merging the current branch.
